name: build
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.x"
      - run: uv pip install --system mkdocs \
              mkdocs-material \
              mkdocstrings-python \
              mkdocs-jupyter \
              markdown_include \
              overviewpy
      - run: mkdocs gh-deploy --force --clean --verbose
