name: ci-cd
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
# Allow one concurrent deployment
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
permissions:
  contents: write
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Check-out repository 🐈
      uses: actions/checkout@v4
    - name: Set up uv 🐍
      uses: astral-sh/setup-uv@v5
      with:
        python-version: "3.9"
    - name: Write GH env 🗝️
      run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
    - name: Install package 📦
      run: uv sync --group dev
    - name: Test with pytest 👩‍⚕️
      run: uv run pytest tests/ --cov=overviewpy --cov-report=xml
    - name: Use Codecov to track coverage ✅
      uses: codecov/codecov-action@v4
      with:
        files: ./coverage.xml   # coverage report
